//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BOSSM                       157
#define IDB_BOSSMAP                     157
#define IDB_MONSTER                     158
#define IDB_MAP2                        159
#define IDB_BLUE                        160
#define IDB_WHITE                       161
#define IDB_BITMAP3                     167
#define IDB_GRAY                        167
#define IDB_MAINCHARACTERRIGHTJUMP      168
#define IDB_MAINCHARACTERSTAND          169
#define IDB_MAINCHARACTERWALK1          170
#define IDB_MAINCHARACTERWALK2          171
#define IDB_BITMAP4                     172
#define IDB_MAINCHARACTERWALK3          172
#define IDB_HERORIGHTWALK3_S            173
#define IDB_HERORIGHTWALK3_G            174
#define IDB_HERORIGHTWALK2_S            175
#define IDB_HERORIGHTWALK2_G            176
#define IDB_HERORIGHTWALK1_S            177
#define IDB_HERORIGHTWALK1_G            178
#define IDB_HERORIGHTSTAND_S            179
#define IDB_HERORIGHTSTAND_G            180
#define IDB_HERORIGHTROLL8              181
#define IDB_HERORIGHTROLL7              182
#define IDB_HERORIGHTROLL6              183
#define IDB_HERORIGHTROLL5              184
#define IDB_HERORIGHTROLL4              185
#define IDB_HERORIGHTROLL3              186
#define IDB_HERORIGHTROLL2              187
#define IDB_HERORIGHTROLL1              188
#define IDB_HERORIGHTJUMP_S             189
#define IDB_HERORIGHTJUMP_G             190
#define IDB_HERORIGHTATTACK4_S          191
#define IDB_HERORIGHTATTACK3_S          192
#define IDB_HERORIGHTATTACK2_S          193
#define IDB_HERORIGHTATTACK1_S          194
#define IDB_HEROLEFTWALK3_S             195
#define IDB_HEROLEFTWALK3_G             196
#define IDB_HEROLEFTWALK2_S             197
#define IDB_HEROLEFTWALK2_G             198
#define IDB_HEROLEFTWALK1_S             199
#define IDB_HEROLEFTWALK1_G             200
#define IDB_HEROLEFTSTAND_S             201
#define IDB_HEROLEFTSTAND_G             202
#define IDB_HEROLEFTROLL8               203
#define IDB_HEROLEFTROLL7               204
#define IDB_HEROLEFTROLL6               205
#define IDB_HEROLEFTROLL5               206
#define IDB_HEROLEFTROLL4               207
#define IDB_HEROLEFTROLL3               208
#define IDB_HEROLEFTROLL2               209
#define IDB_HEROLEFTROLL1               210
#define IDB_HEROLEFTJUMP_S              211
#define IDB_HEROLEFTJUMP_G              212
#define IDB_HEROLEFTATTACK4_S           213
#define IDB_HEROLEFTATTACK3_S           214
#define IDB_HEROLEFTATTACK2_S           215
#define IDB_HEROLEFTATTACK1_S           216
#define IDB_BOSSRIGHTSTAND              217
#define IDB_THRONRED                    218
#define IDB_THRONGROW2                  219
#define IDB_THRONGROW1                  220
#define IDB_CACTUSDEAD                  221
#define IDB_CACTUSALIVE                 222
#define IDB_BOSSRIGHTWALK4              223
#define IDB_BOSSRIGHTWALK3              224
#define IDB_BOSSRIGHTWALK2              225
#define IDB_BOSSRIGHTWALK1              226
#define IDB_BOSSRIGHTTHORN3             227
#define IDB_BOSSRIGHTTHORN2             228
#define IDB_BOSSRIGHTTHORN1             229
#define IDB_BOSSRIGHTHITEFFECT5         230
#define IDB_BOSSRIGHTHITEFFECT4         231
#define IDB_BOSSRIGHTHIT6               232
#define IDB_BOSSRIGHTHIT5               233
#define IDB_BOSSRIGHTHIT4               234
#define IDB_BOSSRIGHTHIT3               235
#define IDB_BOSSRIGHTHIT2               236
#define IDB_BOSSRIGHTHIT1               237
#define IDB_BOSSRIGHTDEAD6              238
#define IDB_BOSSRIGHTDEAD5              239
#define IDB_BOSSRIGHTDEAD4              240
#define IDB_BOSSRIGHTDEAD3              241
#define IDB_BOSSRIGHTDEAD2              242
#define IDB_BOSSRIGHTDEAD1              243
#define IDB_BOSSRIGHTCOLLIDE4           244
#define IDB_BOSSRIGHTCOLLIDE3           245
#define IDB_BOSSRIGHTCOLLIDE2           246
#define IDB_BOSSRIGHTCOLLIDE1           247
#define IDB_BOSSLEFTWALK4               248
#define IDB_BOSSLEFTWALK3               249
#define IDB_BOSSLEFTWALK1               250
#define IDB_BOSSLEFTWALK2               251
#define IDB_BOSSLEFTTHORN3              252
#define IDB_BOSSLEFTTHORN2              253
#define IDB_BOSSLEFTTHORN1              254
#define IDB_BOSSLEFTSTAND               255
#define IDB_BOSSLEFTHITEFFECT5          256
#define IDB_BOSSLEFTHITEFFECT4          257
#define IDB_BOSSLEFTHIT6                258
#define IDB_BOSSLEFTHIT5                259
#define IDB_BOSSLEFTHIT4                260
#define IDB_BOSSLEFTHIT3                261
#define IDB_BOSSLEFTHIT2                262
#define IDB_BOSSLEFTHIT1                263
#define IDB_BOSSLEFTDEAD6               264
#define IDB_BOSSLEFTDEAD5               265
#define IDB_BOSSLEFTDEAD3               266
#define IDB_BOSSLEFTDEAD4               267
#define IDB_BOSSLEFTDEAD2               268
#define IDB_BOSSLEFTDEAD1               269
#define IDB_BOSSLEFTCOLLIDE4            270
#define IDB_BOSSLEFTCOLLIDE3            271
#define IDB_BOSSLEFTCOLLIDE2            272
#define IDB_BOSSLEFTCOLLIDE1            273
#define IDB_BITMAP5                     274
#define IDB_PROPSBOOK                   274
#define IDB_SOURCEGRASSFAST             275
#define IDB_PROPSGRASSFAST              276
#define IDB_PROPGRASSFAST               276
#define IDB_PROPSHRIMPBLOOD             277
#define IDB_PROPMOSQUITOJUMP            278
#define IDB_PROPSHRIMPATTACK            279
#define IDB_PROPGUAVAJUICEBLOOD         280
#define IDB_PROPBANANAATTACK            281
#define IDB_PROPSBOOKCHOICE             282
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        283
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
